import React from 'react';
import { Sparkles } from 'lucide-react';

export default function CommunityAIBadge({ isAI, className = '' }) {
  if (!isAI) return null;
  return <span className={`nx-comm-ai-badge ${className}`.trim()} title="Identified as AI-generated by Community Prerolls">
    <Sparkles size={11} aria-hidden="true" /> AI-generated
  </span>;
}
