name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version tag to publish (e.g. 1.2.2)
        required: true
        default: 1.2.2
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and push multi-arch image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive version
        id: v
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "ver=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            ref="${GITHUB_REF##*/}"
            echo "ver=${ref#v}" >> "$GITHUB_OUTPUT"
          fi

      - name: Resolve Dockerfile path
        id: df
        shell: bash
        run: |
          if [[ -f "Dockerfile" ]]; then
            echo "DOCKERFILE=Dockerfile" >> "$GITHUB_ENV"
          elif [[ -f "NeXroll/Dockerfile" ]]; then
            echo "DOCKERFILE=NeXroll/Dockerfile" >> "$GITHUB_ENV"
          else
            echo "No Dockerfile found in repository root or NeXroll/." >&2
            echo "Workspace listing:"
            ls -la
            exit 1
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            APP_VERSION=${{ steps.v.outputs.ver }}
          tags: |
            jbrns/nexroll:${{ steps.v.outputs.ver }}
            jbrns/nexroll:latest
