name: Docker Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'NeXroll/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (default: latest)'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(grep -o 'version = "[^"]*"' NeXroll/version.py | cut -d'"' -f2)
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building NeXroll version: ${VERSION}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jbrns/nexroll:latest
            jbrns/nexroll:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=jbrns/nexroll:buildcache
          cache-to: type=registry,ref=jbrns/nexroll:buildcache,mode=max
          build-args: |
            APP_VERSION=${{ steps.version.outputs.version }}

      - name: Image scan summary
        run: |
          echo "✅ Docker image successfully built and pushed"
          echo "📦 Image tags:"
          echo "  - jbrns/nexroll:latest"
          echo "  - jbrns/nexroll:${{ steps.version.outputs.version }}"
          echo ""
          echo "🔍 Security scanning:"
          echo "  Docker Hub will automatically scan the image for vulnerabilities"
          echo "  Check results at: https://hub.docker.com/r/jbrns/nexroll"
